name: "Paper-Test-Plugin"
version: "1.0"
main: "io.papermc.testplugin.TestPlugin"
description: Paper Test Plugin
api-version: '1.20'
bootstrapper: io.papermc.testplugin.TestPluginBootstrap
loader: io.papermc.testplugin.TestPluginLoader
libraries:
  - io.github.monun:invfx-core:3.3.2